site_name: CANOPIE-HPC
repo_name: supercontainers/canopie-hpc
repo_url: https://github.com/supercontainers/canopie-hpc
edit_uri: edit/main/docs/
site_url: https://canopie-hpc.org/
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - meta
extra:
  social:
    - icon: fontawesome/brands/slack
      link: http://bit.ly/hpccslack
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Call for Papers: cfp.md
  - Topics: topics.md
  - Organizers: organizers.md
  - Program: program.md
  - Previous Workshops:
    - SC22:
      - Home: prev/2022/index.md
      - Call for Papers: prev/2022/cfp.md
      - Organizers: prev/2022/organizers.md
      - Program: prev/2022/program.md
      - Topics: prev/2022/topics.md
    - SC21:
      - Home: prev/2021/index.md
      - Call for Papers: prev/2021/cfp.md
      - Organizers: prev/2021/org.md
      - Program: prev/2021/program.md
      - Topics: prev/2021/topics.md
    - SC20:
      - Home: prev/2020/index.md
      - Organizers: prev/2020/org.md
      - Program: prev/2020/program.md
      - Topics: prev/2020/topics.md
    - SC19:
      - Home: prev/2019/index.md
      - Call for Papers: prev/2019/cfp.md
      - Organizers: prev/2019/org.md
      - Program: prev/2019/program.md
      - Topics: prev/2019/topic.md

